substitutions:
  device_description: ESPHome MHI-AC-Ctrl-ESPHome
  deviceid: "airco_woonkamer"
  devicename: ${deviceid}
  friendly_name: "Airco woonkamer"

# General settings: captive portal, logger, api, ota, time, restart, webserver, wifi
# General sensors: status, uptime, version, wifi info etc
# Airco common: MHI-AC-Ctrl-ESPHome, climate, sensors, api services shared between the 4 a/c units
packages:
  general_settings: !include includes/general_settings.yaml
  general_sensors: !include includes/general_sensors.yaml
  airco_common: !include includes/airco_common.yaml

# Specific external temperature sensor for this device
sensor:
  - platform: homeassistant
    id: room_temperature_sensor
    entity_id: climate.woonkamer
    attribute: current_temperature

# Override the initial horizontal and vertical vanes positions
MhiAcCtrl:
  initial_horizontal_vanes_position: 1 # Left/Center
  initial_vertical_vanes_position: 5 # Swing
