substitutions:
  name: bt-proxy-1st-floor
  friendly_name: BT Proxy 1st floor
  device_description: Bluetooth proxy op de 1e verdieping

# General settings: captive portal, logger, api, ota, time, restart, webserver, wifi
# General sensors: status, uptime, version, wifi info etc
# BT Proxy common: shared config for all BT Proxy devices
packages:
  general_settings: !include includes/general_settings.yaml
  general_sensors: !include includes/general_sensors.yaml
  bt_proxy_common: !include includes/bt_proxy_common.yaml
