substitutions:
  devicename: deurbel
  upper_devicename: Deurbel

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  manual_ip:
    static_ip: !secret wifi_static_ip_deurbel

# General settings: captive portal, logger, api, ota, time, restart switch, wifi
# General sensors: status, uptime, version, wifi info
packages:
  general_settings: !include general_settings.yaml
  general_sensors: !include general_sensors.yaml

binary_sensor:
  - platform: gpio
    pin: D4
    name: "${upper_devicename}"
    filters:
      - invert:
      - delayed_off: 100ms
