wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${upper_devicename} hotspot
    password: !secret wifi_fallback_password
  manual_ip:
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

button:
  - platform: restart
    name: ${upper_devicename} Restart
