substitutions:
  name: open-air-mini
  friendly_name: Open Air Mini
  device_description: Mechanische ventilatie DucoBox Silent

################ Generics ################
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "${device_description}"

esp32:
  board: esp32dev

# General settings: captive portal, logger, api, ota, time, restart switch, wifi
# General sensors: status, uptime, version, wifi info etc
packages:
  general_settings: !include includes/general_settings.yaml
  general_sensors: !include includes/general_sensors.yaml

web_server:

globals:
  - id: disconnected_default_fan_speed
    type: int
    restore_value: no
    initial_value: "25"

uart:
  #UART For Sensor 1
  - rx_pin: GPIO13
    tx_pin: GPIO12
    baud_rate: 9600
    id: uart_sensor_1
  #UART For Sensor 2
  - rx_pin: GPIO25
    tx_pin: GPIO26
    baud_rate: 9600
    id: uart_sensor_2

i2c:
  #I2C For Sensor 1
  - id: i2c_sensor_1
    sda: GPIO19
    scl: GPIO18
    scan: false
    frequency: 400kHz
  #I2C For Sensor 2
  - id: i2c_sensor_2
    sda: GPIO16
    scl: GPIO4
    scan: false
    frequency: 400kHz

# Status led
status_led:
  pin:
    number: GPIO33

#PWM output for controlling the motor.
output:
  - platform: ledc
    pin: GPIO15
    inverted: true
    id: open_air_mini

fan:
  - platform: speed
    output: open_air_mini
    name: "Open AIR Mini"
    id: fan_motor

sensor:
  - platform: pulse_counter
    pin: GPIO14
    unit_of_measurement: "RPM"
    name: "AIR Mini RPM"

script:
  - id: disconnected_mode
    mode: single
    then:
      - logger.log: "Disconnected Mode Triggered"
      - fan.turn_on:
          id: fan_motor
          speed: !lambda |-
            return id(disconnected_default_fan_speed);

interval:
  - interval: 30s
    then:
      - logger.log: "API Connectivity Check for Disconnected Mode"
      - if:
          condition:
            not:
              api.connected:
          then:
            - logger.log: "API disconnected, starting disconnected mode"
            - script.execute: disconnected_mode
          else:
            - logger.log: "API connected, let HA control the box"
            - script.stop: disconnected_mode
