substitutions:
  devicename: sonoff_basic
  upper_devicename: Sonoff basic

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  manual_ip:
    static_ip: !secret wifi_static_ip_sonoff_basic

# General settings: captive portal, logger, api, ota, time, restart switch, wifi
# General sensors: status, uptime, version, wifi info
packages:
  general_settings: !include general_settings.yaml
  general_sensors: !include general_sensors.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${upper_devicename}
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
