substitutions:
  devicename: staande-lamp
  upper_devicename: Staande lamp

esphome:
  name: $devicename

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

button:
  - platform: restart
    name: ${upper_devicename} Restart

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${upper_devicename} Status

sensor:
  - platform: uptime
    name: ${upper_devicename} uptime
    update_interval: 300s

switch:
  - platform: gpio
    name: ${upper_devicename}
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: version
    name: ${upper_devicename} Version
