substitutions:
  devicename: weerhuisje
  friendly_name: Weerhuisje
  device_description: Zelfgebouwd weerhuisje in onze achtertuin

################ Generics ################
esphome:
  name: $devicename
  friendly_name: ${friendly_name}
  comment: "${device_description}"

esp8266:
  board: nodemcuv2

# General settings: captive portal, logger, api, ota, time, restart switch, wifi
# General sensors: status, uptime, version, wifi info etc
packages:
  general_settings: !include includes/general_settings.yaml
  general_sensors: !include includes/general_sensors.yaml

################ Components ################
# Enable UART for SDS011
uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600

# Enable i2c for BME280
i2c:
  sda: D5
  scl: D6
  scan: false

################ Sensors ################
sensor:
  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 20min

  - platform: bme280_i2c
    update_interval: 120s
    address: 0x76
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
