################ Common airco code ################
logger:
  logs:
    component: ERROR # Mute "Component MhiAcCtrl took a long time for an operation" warnings
    mhi.platform: INFO # Mute external temperature sensor warnings

external_components:
  - source: github://ginkage/MHI-AC-Ctrl-ESPHome@master
    components: [MhiAcCtrl]
    refresh: 0s

MhiAcCtrl:
  external_temperature_sensor: room_temperature_sensor
  frame_size: 33
  room_temp_timeout: 1800

api:
  reboot_timeout: 0s
  services:
    - service: set_external_room_temperature
      variables:
        temperature_value: float # temperature to set in Celsius
      then:
        - climate.mhi.set_external_room_temperature:
            temperature: !lambda "return temperature_value;"

climate:
  - platform: MhiAcCtrl
    name: "${friendly_name}"
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

sensor:
  - platform: MhiAcCtrl
    outdoor_temperature:
      name: "Outdoor temperature"
    return_air_temperature:
      name: "Return air temperature"
    outdoor_unit_fan_speed:
      name: "Outdoor unit fan speed"
    indoor_unit_fan_speed:
      name: "Indoor unit fan speed"
    compressor_frequency:
      name: "Compressor frequency"
      disabled_by_default: true
    indoor_unit_total_run_time:
      name: "Indoor unit total run time"
    compressor_total_run_time:
      name: "Compressor total run time"
    current_power:
      name: "Current power"
    energy_used:
      name: "Energy used"
    error_code:
      name: "Error code"
    ### Disabled by default, but can be enabled if needed
    indoor_unit_thi_r1:
      name: "Indoor (U-bend) HE temp 1"
      disabled_by_default: true
    indoor_unit_thi_r2:
      name: "Indoor (capillary) HE temp 2"
      disabled_by_default: true
    indoor_unit_thi_r3:
      name: "Indoor (suction header) HE temp 3"
      disabled_by_default: true
    outdoor_unit_tho_r1:
      name: "Outdoor HE temp"
      disabled_by_default: true
    outdoor_unit_expansion_valve:
      name: "Outdoor unit exp. valve"
      disabled_by_default: true
    outdoor_unit_discharge_pipe:
      name: "Outdoor unit discharge pipe"
      disabled_by_default: true
    outdoor_unit_discharge_pipe_super_heat:
      name: "Outdoor unit discharge pipe super heat"
      disabled_by_default: true
    protection_state_number:
      name: "Compressor protection code"
      disabled_by_default: true
    vanes_pos:
      name: "Vanes"
      disabled_by_default: true
    vanesLR_pos:
      name: "Vanes Left/Right"
      disabled_by_default: true

select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: Fan Control Up Down
    horizontal_vanes:
      name: Fan Control Left Right
    fan_speed:
      name: "Fan Speed"

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "3D Auto"

text_sensor:
  - platform: MhiAcCtrl
    protection_state:
      name: "Compressor protection status"
      disabled_by_default: true
