################ Generics ################
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "${device_description}"
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

################ Components ################
esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

################ Remove webserver ################
web_server: !remove
