################ Generics ################
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: "${device_description}"
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true

################ Components ################
bluetooth_proxy:
esp32_ble_tracker:

################ Remove webserver ################
web_server: !remove
