binary_sensor:
  - platform: status
    name: Status

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 300s
  - platform: wifi_signal
    name: WiFi signaal
    update_interval: 300s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Address
  - platform: version
    name: Version
